name: Build Size Report

on:
  pull_request_target:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # Workaround for https://github.com/preactjs/compressed-size-action/issues/54
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          build-script: 'build:v2:en'
          pattern: '{website/build/assets/js/main*js,website/build/assets/css/styles*css,website/build/index.html,website/build/blog/**/introducing-docusaurus/*,website/build/docs/introduction/index.html}'
          strip-hash: '\.([^;]\w{7})\.'
          minimum-change-threshold: 30
          compression: 'none'
